apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
        - name: mywebsite
          image:{{IMAGE_URI}}
          ports:
            - containerPort: 8080  # Port on which your application listens
          readinessProbe:
            httpGet:
              path: /actuator/health  # Adjust as per your application health endpoint
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
