apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebsite-deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: mywebsite
  template:
    metadata:
      labels:
        app: mywebsite
    spec:
      containers:
        - name: mywebsite-container
          image: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.get-ecr-image-digest.outputs.image_digest }}
          ports:
            - containerPort: 80  # Port your application listens on
          # Add more configuration as needed, e.g., env variables, volumes, etc.

