apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80  # Service port
      targetPort: 8080  # Container port
  type: LoadBalancer  # Expose the service to external traffic
