apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  type: LoadBalancer
  ports:
    - port: 80  # Port on the service
      targetPort: 8080  # Port your application listens on inside the pods
  selector:
    app: mywebsite  # Labels to select pods to load balance traffic to
