name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the build on

env:
  AWS_REGION: your-aws-region
  AWS_ACCOUNT_ID: your-aws-account-id
  ECR_REPO_NAME: your-ecr-repository-name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
         registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
         region: ${{ env.AWS_REGION }}

      - name: Debug AWS Credentials
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          aws configure list

      - name: Check AWS CLI Version
        run: aws --version


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build the Docker image
        run: |
          docker build -t $ECR_REPO_NAME .
      
      - name: Tag the Docker image
        run: |
          docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      
      - name: Push Docker image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:latest

      - name: Logout of Amazon ECR
        run: |
          docker logout $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
