name: Build and Push to ECR and Deploy to EKS

on:
  push:
    branches:
      - main  # Replace with your main branch name
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Do you want to deploy?'
        required: true
        default: 'no'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Repository Contents
        run: ls -R

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        if: github.event_name == 'push' || github.event.inputs.confirmation == 'yes'
        run: |
          docker build -t ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/webapp:${{ github.run_number }} .
          docker tag ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/webapp:${{ github.run_number }} ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/webapp:latest

      - name: Push Docker image to ECR
        if: github.event_name == 'push' || github.event.inputs.confirmation == 'yes'
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/webapp:${{ github.run_number }}
          docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}/webapp:latest

      
