name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Replace with your main branch name
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Do you want to deploy?'
        required: true
        default: 'no'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change to mywebsite directory
        run: cd mywebsite
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Docker image and Push to ECR
        if: github.event_name == 'push' || github.event.inputs.confirmation == 'yes'
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}/webapp:${{ github.run_number }} .
          docker tag ${{ secrets.ECR_REPOSITORY }}/webapp:${{ github.run_number }} ${{ secrets.ECR_REPOSITORY }}/webapp:latest
          docker push ${{ secrets.ECR_REPOSITORY }}/webapp:${{ github.run_number }}
          docker push ${{ secrets.ECR_REPOSITORY }}/webapp:latest
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deployment Skipped (No EKS Configuration)
        if: github.event_name == 'push' || github.event.inputs.confirmation == 'yes'
        run: echo "No deployment to EKS configured. Only pushed to ECR."
